eadb:
  image: mysql:5.6
  restart: unless-stopped
  env_file: mysql.env
  volumes:
    - eadb:/var/lib/mysql
eaweb:
  build: .
  restart: unless-stopped
  ports:
    - "8020:80"
  volumes:
    - eacode:/var/www/html
  links:
    - eadb
